
HIGH_TEMPERATURE_THRESHOLD = 85.0

HIGH_VIBRATION_THRESHOLD = 0.8

LOW_PRESSURE_THRESHOLD = 0.25

LOW_FLOW_RATE_THRESHOLD = 0.25

HIGH_TEMPERATURE_WEIGHT = 2

HIGH_VIBRATION_WEIGHT = 2

LOW_PRESSURE_WEIGHT = 2

LOW_FLOW_RATE_WEIGHT = 1

COOLING_COMBINATION_WEIGHT = 3

ANOMALY_SCORE_THRESHOLD = 5
SAVE_ALL_DETECTIONS = False

DETECTION_HISTORY_PATH = "experiments/outputs/jsonl/detection_history.jsonl"